# setup_task_scheduler.ps1
# Run this once in an elevated PowerShell session to register the daily digest task.
# Usage: Right-click → "Run with PowerShell" (as Administrator)

param(
    [string]$DigestDir  = $PSScriptRoot,           # folder containing digest.py
    [string]$PythonExe  = "python",                # e.g. "C:\Python312\python.exe"
    [string]$TaskName   = "DailyDigest",
    [string]$StartTime  = "06:30"                  # 6:30 AM local time
)

$scriptPath = Join-Path $DigestDir "digest.py"

if (-not (Test-Path $scriptPath)) {
    Write-Error "digest.py not found at: $scriptPath"
    exit 1
}

# Build the action: python digest.py  (working dir = $DigestDir so .env / sources.yaml resolve)
$action = New-ScheduledTaskAction `
    -Execute $PythonExe `
    -Argument "`"$scriptPath`"" `
    -WorkingDirectory $DigestDir

# Daily trigger at 06:30 local time
$trigger = New-ScheduledTaskTrigger -Daily -At $StartTime

# Run whether or not the user is logged in; store the password securely
$settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 15) `
    -StartWhenAvailable `
    -WakeToRun

# Use the current user account
$principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType S4U `
    -RunLevel Limited

# Remove existing task if present
if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "Removed existing task: $TaskName"
}

Register-ScheduledTask `
    -TaskName  $TaskName `
    -Action    $action `
    -Trigger   $trigger `
    -Settings  $settings `
    -Principal $principal `
    -Description "Daily morning digest email — generated by digest.py"

Write-Host ""
Write-Host "✓ Task '$TaskName' registered successfully."
Write-Host "  Schedule : Daily at $StartTime (local time)"
Write-Host "  Script   : $scriptPath"
Write-Host "  Python   : $PythonExe"
Write-Host ""
Write-Host "To run immediately for testing:"
Write-Host "  Start-ScheduledTask -TaskName '$TaskName'"
Write-Host ""
Write-Host "To view in Task Scheduler GUI:"
Write-Host "  taskschd.msc"
